# Stage 1: Install dependencies
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

RUN npm ci

# Stage 2: Build the application
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .


# NEXT_PUBLIC variable:
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_EXTERNAL_IMAGE_BASE
ARG NEXT_PUBLIC_CONTACT_PHONE
ARG NEXT_PUBLIC_BKASH_PHONE
ARG NEXT_PUBLIC_NOGOD_PHONE
ARG NEXT_PUBLIC_MESSENGER_URL
ARG NEXT_PUBLIC_LOGIN_PAGE_TITLE
ARG NEXT_PUBLIC_PUSHER_APP_KEY
ARG NEXT_PUBLIC_PUSHER_HOST
ARG NEXT_PUBLIC_PUSHER_PORT
ARG NEXT_PUBLIC_PUSHER_SCHEME
ARG NEXT_PUBLIC_PUSHER_APP_CLUSTER
ARG NEXT_PUBLIC_META_PIXEL_ID

# ENV so the Next.js build process can see them
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_EXTERNAL_IMAGE_BASE=$NEXT_PUBLIC_EXTERNAL_IMAGE_BASE
ENV NEXT_PUBLIC_CONTACT_PHONE=$NEXT_PUBLIC_CONTACT_PHONE
ENV NEXT_PUBLIC_BKASH_PHONE=$NEXT_PUBLIC_BKASH_PHONE
ENV NEXT_PUBLIC_NOGOD_PHONE=$NEXT_PUBLIC_NOGOD_PHONE
ENV NEXT_PUBLIC_MESSENGER_URL=$NEXT_PUBLIC_MESSENGER_URL
ENV NEXT_PUBLIC_LOGIN_PAGE_TITLE=$NEXT_PUBLIC_LOGIN_PAGE_TITLE
ENV NEXT_PUBLIC_PUSHER_APP_KEY=$NEXT_PUBLIC_PUSHER_APP_KEY
ENV NEXT_PUBLIC_PUSHER_HOST=$NEXT_PUBLIC_PUSHER_HOST
ENV NEXT_PUBLIC_PUSHER_PORT=$NEXT_PUBLIC_PUSHER_PORT
ENV NEXT_PUBLIC_PUSHER_SCHEME=$NEXT_PUBLIC_PUSHER_SCHEME
ENV NEXT_PUBLIC_PUSHER_APP_CLUSTER=$NEXT_PUBLIC_PUSHER_APP_CLUSTER
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID
ENV NEXT_TELEMETRY_DISABLED 1

# Execute the standard build
RUN npm run build

# Stage 3: Production runner
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]